# Configuration for service startup
onboard_path: "/home/yousif/Projects/Uni/RadarSimulation/OnboardSoftware"
onboard_name: "onboard-yolo.py"
viz_path: "/home/yousif/Projects/Uni/RadarSimulation/Visualization/"
api_path: "/home/yousif/Projects/Uni/RadarSimulation/Visualization/DB_API/main.py"
db_path: "/home/yousif/Projects/Uni/RadarSimulation/Visualization/DB_API/"
conda_env: "deep_learning"

# Optional configuration (not yet implemented, for future use)
db_startup_delay: 1 # seconds to wait for DB initialization
enable_services:
  db: true
  api: true
  onboard: true
  viz: true
