# Simulation Configurations
sceneName: KhorfakkanCoastline # [OceanMain, KhorfakkanCoastline] Choose OceanMain when generating a dataset and KhorfakkanCoastline when running the entire system.
nScenarios: 400
scenarioTimeLimit: 120
screen-fullscreen: 0

# Radar Configurations
nRadars: 1
radarRows: 3
radarPower: 50 # Watts
radarGain: 30 # dB
waveLength: 0.0031228381 # meters (for 9.5 GHz)
antennaVerticalBeamWidth: 22
antennaHorizontalBeamWidth: 1.2
radarImageRadius: 1000
rainRCS: 0.001

# Ship Configurations
nships: [30, 100] # Range [0, 120]
nLocations: [7, 10] # Range [5, 30]
speed: [12, 18] # Knots       # Range [1, 30]
coordinateSquareWidth: 30000

# Weather and Waves
# The simulation loops through these conditions every scenario.
# The list length does not have to match the number of scenarios.
# Once the list reaches its end, it will restart picking the conditions from its beginning.

# Valid values "Clear", "ModerateRain", "HeavyRain", "VeryHeavyRain", "Shower", "CloudBurst"
weather: [Clear, ModerateRain, HeavyRain, VeryHeavyRain, Shower, CloudBurst]
waves: [Calm, Moderate] # Valid values "Calm", "Moderate"
proceduralLand: [True, False] # Valid values 'True' (Generate Procedural land), 'False' (Do not generate Procedural Land)

# Dataset Generation
# This is for generating a dataset while running the entire system. generateDataset.py ignores the below settings.
generateDataset: True
unityBuildDirectory: C:\Users\monsi\Downloads\ProjectBuild\RadarProject.exe
outputDirectory: C:\Users\monsi\Downloads\output # The dataset JSON files output directory 
