# Dockerfile
FROM postgres:15

# Environment variables for the database
ENV POSTGRES_DB=radar_tracking
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres


# Expose PostgreSQL port
EXPOSE 5432
