# Simulation Configurations
sceneName: OceanMain      # [OceanMain, KhorfakkanCoastline]
nScenarios: 400
scenarioTimeLimit: 60
screen-fullscreen: 0

# Radar Configurations
nRadars: 2
radarRows: 3
radarPower: 50  # Watts
radarGain: 30     # dB
frequency: 0.0031228381  # meters (for 9.5 GHz)
antennaVerticalBeamWidth: 22
antennaHorizontalBeamWidth: 1.2
radarImageRadius: 1000
rainRCS: 0.001

# Ship Configurations
nships: [30, 100]                # Range [0, 120]
nLocations: [7, 10]             # Range [5, 30]
speed: [12, 18]   # Knots       # Range [1, 30]
coordinateSquareWidth: 30000

# Weather and Waves
# Simulation Loops through these conditions every scenario
# The list length do not have to match, 
# The list will start from the beginning once it reaches the end of the list

# Valid values "Clear", "ModerateRain", "HeavyRain", "VeryHeavyRain", "Shower", "CloudBurst"
weather: [Clear, ModerateRain, HeavyRain, VeryHeavyRain, Shower, CloudBurst] 
waves: [Calm, Moderate]                # Valid values "Calm", "Moderate"
proceduralLand: [True, False]          # Valid values 'True' (Generate Procedural land), 'False' (Do not generate Procedural Land)

# Dataset Generation
# generateDataset.py ignores the below settings
generateDataset: true
unityBuildDirectory: ~/Downloads/project.x86_64
outputDirectory: ~/Downloads/output
