# Simulation Configurations
sceneName: OceanMain      # [OceanMain, KhorfakkanCoastline]
nScenarios: 100
scenarioTimeLimit: 60
screen-fullscreen: 0

# Radar Configurations
nRadars: 2
radarRows: 3
radarPower: 1000  # Watts
radarGain: 30     # dB
waveLength: 0.03  # meters
radarImageRadius: 1000
verticalAngle: 30
beamWidth: 2
rainRCS: 0.001

# Ship Configurations
nships: [30, 100]                # Range [0, 120]
nLocations: [7, 10]             # Range [5, 30]
speed: [12, 18]   # Knots       # Range [1, 30]
coordinateSquareWidth: 30000

# Weather and Waves
# Simulation Loops through these conditions every scenario
# The list length do not have to match, 
# The list will start from the beginning once it reaches the end of the list
weather: [Clear, LightRain, HeavyRain] # Valid values "Clear", "LightRain", "HeavyRain"
waves: [Calm, Moderate]                # Valid values "Calm", "Moderate"
proceduralLand: [True, False]          # Valid values 'True' (Generate Procedural land), 'False' (Do not generate Procedural Land)

# Dataset Generation
# generateDataset.py ignores the below settings
generateDataset: true
unityBuildDirectory: ~/Downloads/project.x86_64
outputDirectory: ~/Downloads/output