# Simulation Configurations
# sceneName: KhorfakkanCoastline      # Scene to start the simulation in. Has two options: [OceanMain, KhorfakkanCoastline]
nScenarios: 100
scenarioTimeLimit: 60
screen-fullscreen: 0

# Radar Configurations
nRadars: 2
radarRows: 3
radarPower: 1000  # Watts
radarGain: 30     # dB
waveLength: 0.03  # meters
radarImageRadius: 1000
verticalAngle: 30
beamWidth: 2
rainRCS: 0.001

# Ship Configurations
nships: [30, 12]               # Range [0, 120]
nLocations: [7, 10]             # Range [5, 30]
speed: [12, 18]   # Knots       # Range [1, 30]
coordinateSquareWidth: 30000